---
title: "Research"
---

::: {style="font-size: 0.9em;"}
The primary focus of my research is how environmental factors across multiple levels, from individual life experiences to within-family interactions to societal factors, impact the development of mental health problems in young people and adults. See also [my Google Scholar profile](https://scholar.google.com/citations?user=MDH9VfoAAAAJ&hl=en).
:::

::: {style="font-size: 0.8em;"}
## Publication list

\[Last updated: July 2025\]

^34^**Bjørndal, L. D.**, Ebrahimi, O. V., & Bauermeister, S. (2024). The dynamic interplay between mental health difficulties and the family environment in early adolescence. *JCPP Advances*. <https://doi.org/10.1002/jcv2.70037>

^33^**Bjørndal, L. D.**, Røysamb E., Nes, R. B., von Soest, T., & Ebrahimi, O. V. (2024). Financial factors and depression and anxiety: A symptom-specific approach in the general population. *SSM – Mental Health*. <https://doi.org/10.1016/j.ssmmh.2025.100508>

^32^**Bjørndal, L.D.**, Chen, Y., (…), & Fang, F. (2025). Stress resilience and risk of psychiatric disorders after childhood bereavement. *JAMA Network Open*. <https://doi.org/10.1001/jamanetworkopen.2025.19706>

^31^Roettger, T., (...) **Bjørndal, L. D.**, (...), & Hannigan, L. (2025). Transparency in epidemiological analyses of cohort data – A case study of the Norwegian Mother, Father, and Child cohort study (MoBa). *BMC Medical Research Methodology.* <https://doi.org/10.1186/s12874-025-02601-6>

^30^Karstoft, K-I., **Bjørndal, L.D.**, (...), & Hall, Brian. J. (2025). Associations of war exposures, post-migration living difficulties and social support with (complex) PTSD: A cohort study of Ukrainian refugees resettled in Denmark. *Social Science & Medicine*. <https://doi.org/10.1016/j.socscimed.2025.118080>

^29^Prydz, M. B., **Bjørndal, L. D.**, Czajkowski, N. O., Røysamb, E., & Nes, R. B. (2025). Mechanisms of change in a digital Five Ways to Wellbeing Intervention: A network intervention analysis of a randomized controlled trial. *Behaviour Research and Therapy*. <https://doi.org/10.1016/j.brat.2025.104781>

^28^Hegemann, L., Eilertsen, E. M., (...), **Bjørndal, L. D.**, (...), & Hannigan, L. (2025). Direct and indirect genetic effects on early neurodevelopmental traits. (2025). *JCPP*, 1-12. <https://doi.org/10.1111/jcpp.14122>

^27^**Bjørndal, L. D.**, Nes, R. B., Ayorech, Z., Vassend, O., & Røysamb, E. (2024). Multiple social factors are associated with wellbeing when accounting for shared genetic and environmental confounding. *Quality of Life Research*. <https://doi.org/10.1007/s11136-024-03832-8>

^26^Arneberg, V. S., Sundsvold, V., **Bjørndal, L. D.**, & Ystrom, E. Borderline personality disorder symptoms and stressful life events: An evaluation of gene-environment interplay. (2024). *Biological Psychiatry: Global Open Science*. <https://doi.org/10.1016/j.bpsgos.2024.100390>

^25^Lupattelli, A., Branquinho, M., Cardoso, C., Tauqeer, F., **Bjørndal, L. D.**, & Fonseca, A. (2024). Psychometric properties of the Decisional Conflict Scale in a sample of perinatal women with depressive symptoms: A study in Portugal and Norway. *Patient Education and Counseling*, 126, 1-8. <https://doi.org/10.1016/j.pec.2024.108337>

^24^Moreno-Martes, D., Zhao, J., Li, H., Nyberg, F., **Bjørndal, L. D.**, (…), & Morales, D. R. (2024). Impact of the early COVID-19 pandemic on adult mental health-related dispensed medications, hospitalizations and specialist outpatient visits in Norway and Sweden: Interrupted timeseries analysis. *British Journal of Clinical Pharmacology*. <https://doi.org/10.1111/bcp.16044>

^23^Nasrin, T., Tauqeer, F., **Bjørndal, L. D.**, Kittel-Schneider, S., & Lupattelli, A. (2024). Partner support about antidepressant treatment and its association with depressive symptoms in pregnant women, mothers and women planning pregnancy. *Archives of Women’s Mental Health*. <https://doi.org/10.1007/s00737-024-01435-3>

^22^**Bjørndal, L. D.,** Eilertsen, E. M., (...), & Ystrom, E. (2024). Disentangling direct and indirect genetic effects from partners and offspring on maternal depression using trio-GCTA. *Nature Mental Health*. <https://doi.org/10.1038/s44220-024-00207-3>

^21^Ayorech, Z., Torvik, F. A., Cheesman, R., Eilertsen, E. M., Valstad, M., **Bjørndal L. D.**, Røysamb E., Havdahl, A., & Ystrom, E. (2024). The structure of psychiatric comorbidity without selection and assortative mating. *Translational Psychiatry*, 14(1), 1-9. <https://doi.org/10.1038/s41398-024-02768-4>

^20^**Bjørndal, L. D.,** Ebrahimi, O. V., Røysamb, E., Karstoft, K-I., Czajkowski, N. O., & Nes, R. B. (2024). Stressful life events exhibit complex patterns of associations with depressive symptoms in two population-based samples using network analysis. *Journal of Affective Disorders*, 349, 569-576. <https://doi.org/10.1016/j.jad.2024.01.054>

^19^**Bjørndal, L. D.** (2023). Miljøet er sentralt for den psykiske helsen. *Tidsskrift for Norsk Psykologforening*, *60*(11), 686-688.

^18^Metz, K., Lewis, J., Mitchell, J., Chakraborty, S., McLeod, B. D., **Bjørndal L.**, Mildon, R., & Shlonsky, A. (2023). Problem-solving interventions and depression among adolescents and young adults: A systematic review of the effectiveness of problem-solving interventions in preventing or treating depression. *PLOS ONE*. <https://doi.org/10.1371/journal.pone.0285949>

^17^**Bjørndal, L. D.**, Ebrahimi, O. V., Lan, X., Nes, R. B., & Røysamb, E. (2023). Mental health and environmental factors in adults: A population-based network analysis. *American Psychologist*. <https://doi.org/10.1037/amp0001208>

^16^**Bjørndal, L. D.** (2023). The relationship between stressful life events and depression risk. *Nature Reviews Psychology*. <https://doi.org/10.1038/s44159-023-00216-6>

^15^**Bjørndal, L. D.**, Nes, R. B., Czajkowski, N., & Røysamb E. (2023). The structure of wellbeing—a single underlying factor with genetic and environmental influences. *Quality of Life Research*. <https://doi.org/10.1007/s11136-023-03437-7>

^14^Fonseca, A., Branquinho, M., Monteiro, F., Araújo-Pedrosa, A., **Bjørndal**, L. D., & Lupattelli, A. (2023). Treatment options and their uptake among women with symptoms of perinatal depression: An exploratory study in Norway and Portugal. *BJPsych Open*, 9, 1-9. <https://doi.org/10.1192/bjo.2023.56>

^13^Ayorech, Z., Cheesman, R., Eilertsen, E. M., **Bjørndal**, **L. D.,** Røysamb, E., McAdams, T. A., Havdahl, A., & Ystrom, E. (2023) Maternal depression and the polygenic p factor: A family perspective on direct and indirect effects. *Journal of Affective Disorders*, *332*, 159-167. <https://doi.org/10.1016/j.jad.2023.03.043>

^12^**Bjørndal**, L. D., Tauqeer, F., Heiervang, K. S., Clausen, H. K., Heitmann K., & Lupattelli, A. (2022). Perception of risk of adverse neurodevelopmental outcomes in offspring related to antidepressant, other psychotropics and mental illness exposure in pregnancy and breastfeeding. *BMJ Open*, *12*(9), 1-11. <https://doi.org/10.1136/bmjopen-2022-061159>

^11^**Bjørndal**, L. D., Kendler, K. S., Reichborn-Kjennerud, T., & Ystrom, E. (2022) Stressful life events increase the risk of major depressive episodes: A population-based twin study. *Psychological Medicine*, 1-9. <https://doi.org/10.1017/S0033291722002227>

^10^Finch, M., Featherston R., Chakraborty S., **Bjørndal, L.**, (…), & Shlonsky, A. (2022). Interventions that Address Institutional Child Maltreatment: An Evidence and Gap Map. *Research on Social Work Practice*, *33*(4), 437-459. <https://doi.org/10.1177/10497315221115867>

^9^Ruggeri, K., Panin, A., Vdovic, M., Većkalov, B., (…), **Bjørndal, L. D.,** (…), & García-Garcon, E. (2022). The globalizability of temporal discounting. *Nature Human Behaviour*, 6, 1386-1397. <https://doi.org/10.1038/s41562-022-01392-w>

^8^Saraiva, R., Bertoldo G., **Bjørndal** **L. D.,** Bunghez, C., Lofthus, I., McGill, L., Richardson, S., & Stadel, M. (2022). Improving the evaluation of eyewitness evidence in legal decision-making: Testing an active versus passive teaching aid. *Applied Cognitive Psychology*, *36*(3), 520-535. <https://doi.org/10.1002/acp.3938>

^7^**Bjørndal, L. D.,** Brennen, T., & Magnussen, S. J. (2021). Norske dommeres kunnskap om påliteligheten av øyevitneforklaringer – 12 år senere. *Lov & Rett*, *9*(60), 461-472. <https://doi.org/10.18261/issn.1504-3061-2021-09-03>

^6^Sumampouw, N., **Bjørndal, L. D**., Magnussen, S., Otgaar, H., & Brennen, T. (2021). Knowledge about eyewitness testimony: A survey of Indonesian police officers and psychologists. *Psychology, Crime & Law, 28(*8), 763-777. <https://doi.org/10.1080/1068316X.2021.1962868>

^5^Ruggeri, K., Većkalov, B., Bojanić, L., Andersen, T. L., Ashcroft- Jones, S., Ayscaxli, N., (...), **Bjørndal L. D.**, (…), & Folke, T. (2021). The general fault in our fault lines. *Nature Human Behaviour*, *5,* 1369-1380. <https://doi.org/10.1038/s41562-021-01092-x>

^4^Finch, M., Albers, B., (…), **Bjørndal, L.,** Shlonsky, A. (2021). Institutional responses to child maltreatment. *Campbell Systematic Reviews*, *17*(1), 1-104. <https://doi.org/10.1002/cl2.1139>

^3^**Bjørndal, L**. **D**., McGill, L., Magnussen, S., Richardson, S., Saraiva, R., Stadel, M., & Brennen, T. (2020). Norwegian judges’ knowledge of factors affecting eyewitness testimony: A 12-year follow-up. *Psychiatry, Psychology and Law*, *12*(5), 665-682. <https://dx.doi.org/10.1080/13218719.2020.1837028>

^2^Ruggeri, K., Alí, S., Berge, M. L., Bertoldo, G., **Bjørndal, L. D**., Cortijos-Bernabeu, A., ... Folke, T. (2020). Replicating patterns of Prospect Theory for decision under risk. *Nature Human Behaviour*, *4*(6), 622-633. <https://doi.org/10.1038/s41562-020-0886-x>

^1^Albers, B., Fiennes, C., Shlonsky, A., Finch, M., **Bjørndal, L.**, Hennessy, J., … Mildon, R. (2019). Evidence and gap map protocol: Institutional responses to child maltreatment. *Campbell Systematic Reviews*, *15*(3), 1-24. <https://doi.org/10.1002/cl2.1039>

## Manuscripts undergoing peer review

**Bjørndal, L. D.**, Ebrahimi, O. V., & Bauermeister, S. (2024). The dynamic interplay between mental health difficulties and the family environment in early adolescence. <https://osf.io/preprints/psyarxiv/9j4hp>

**Bjørndal, L. D.**, Corfield, E. C., (…), Ask, H., & Havdahl, A. (2025). Avoidant restrictive food intake phenotypes: Prevalence, developmental characteristics, and genetic architecture. <https://osf.io/preprints/psyarxiv/92dba_v1>

**Bjørndal, L. D.**, Hegemann, L., (…), & Watson, H. (2025). Investigating relationships between genetic risk, childhood maltreatment and eating disorders. <https://osf.io/preprints/psyarxiv/fy2xn_v1>

**Bjørndal, L. D.**, Wootton, R. E., (…), Ask, H., & Havdahl, A. (2024). Unravelling symptom-specific polygenic effects on maternal mental health during the perinatal period and postpartum. <https://osf.io/preprints/psyarxiv/zxdfg>

**Bjørndal, L. D.**, Røysamb E., Nes, R. B., von Soest, T., & Ebrahimi, O. V. (2024). Financial factors and depression and anxiety: A symptom-specific approach in the general population. <https://osf.io/preprints/psyarxiv/cz65n>

Ahmadzadeh, Y. I., Eilertsen, E. M., (...), **Bjørndal, L. D.,** (...), & McAdams, T. A. (2024). Are mothers’ prenatal emotional symptoms influenced by the foetal genome? Exploring the possibility of offspring to parent effects during pregnancy. Preprint: <https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4989215>

Karl, V., **Bjørndal, L. D.,** (...), & Tamnes, C. K. (2024). Symptom-specific links between internalizing problems and functional connectivity in adolescents: A network analysis. <https://doi.org/10.31234/osf.io/cv9q4>

Tamnes, C., (...), **Bjørndal, L. D.**, (...), & von Soest, T. (2024). The nature of the relation between mental illbeing and wellbeing. Preprint: <https://osf.io/preprints/psyarxiv/9jk2x>
:::
